### ISSUE TITLE
todo list

### ISSUE THREAD

**Issue by xerroxcopy** [xerroxcopy/aiit-tex-bulletin#3]
- [x] #15
- [ ] アブストラクト
  - [x] 表示する
  - [x] #5
  - [x] #6
  - [x] #4
  - [x] keywordsをつける
  - [x] date消す
- [x] １ページめのtitlepsを他と変える
- [ ] セクション
  - [x] #7
  - [x] #9
  - [x] #14
- [ ] 本文
  - [x] #8
  - [x] #10
  - [x] #13
- [x] #18
- [x] #11
   - [x] リンクを貼る
- [ ] 表の例を増やす（全幅バージョン）
- [ ] DOIを出版に先立って発行して入力する方法（著者が入力する？）
  - [ ] DOIのダミーURLリンクを修正
- [x] #29
- [x] #30
- [x] #12
- [x] ダウンロードすると動かない問題の修正？
- [x] 英語版を作る
  - [ ] 字下げを大きくする
  - [ ] 行間を小さくする
  - [ ] jlreqではなく何を使うべきか検討
- [ ] 18号以降のテンプレート更新のための紀要編集委員用のガイドラインを作成する
  - [ ] 変更点：フッターとヘッダー、題名、著者名
- [ ] Word版フィードバック・改善・拡張
  - [x] 「参考文献」表示するのか統一
  - [x]  Palatinoを用いたWord版テンプレートの作成
 - [ ] 2024年度
   - [ ] ルーチン
     - [ ] ヘッダーの変更：Vol++
       - [x] Word (ja)
       - [ ] Word (en)
       - [x] LaTeX (ja)
       - [ ] LaTeX (en)
     - [x] 題名と本文冒頭年度の変更：yyyy年度版++　（一括置換？）
     - [ ] フッターの変更：Received: yyyy-mm-dd; Published online: yyyy-mm-dd
       - [x] Word (ja)
       - [ ] Word (en)
       - [x] LaTeX (ja)
       - [ ] LaTeX (en)
   - [x] #19
   - [x] #20 
   - [x] #21 
   - [x] #22
   - [x] #23
   - [x] #24
   - [x] #25
     - [x]  Word
     - [x] #31
   - [x] #26
   - [x] #27
   - [x] #28
   - [x] #32
  - [x] #33 
  - [x] #16
